name: Name

on:
  pull_request:
    branches:[master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: SetupJDK15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
