name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
         name: Test Results
         path: ${{ github.workspace }}/target/surefire-reports/TEST-TestSuite.xml
         reporter: java-junit
         java-version: 17

